version: '3.8'

services:
  service:
    build: ../docker
    container_name: micro-framework
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
    environment:
      - WEBROOT_PATH=/var/www/example/public
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.35
    restart: always
    environment:
      MYSQL_DATABASE: 'microframework'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: "%"
    command:
      - "--default-authentication-plugin=mysql_native_password"
    ports:
      - "3306"
    volumes:
      - mf_database:/var/lib/mysql

volumes:
  mf_database: